### ISSUE TITLE
구글 로그인 시, 405 에러

### ISSUE THREAD

**Issue by webhacking** [okjsp/okky#104]
The specified HTTP `method` is not allowed for the requested resource.

**Comment by parksangwon** [comment]
저도 같은 오류때문에 글 남깁니다. url에 이상한 값들이 있어 지우고 다시 해보니 되는거 같았습니다.

**Comment by 1angerhans** [comment]
혹시 잘못된 값이 어떤 것인지 올려주시면 감사드리겠습니다 :D

**Comment by parksangwon** [comment]
google 로그인 버튼 누르니까 url에

http://okky.kr/article/dissent/320072.json#

가 찍히면서 405 에러 뜹니다.

**Comment by 1angerhans** [comment]
#114 와 연관되어 있습니다.
