### ISSUE TITLE
계정찾기기능 -> 비밀번호 변경이 제대로 되지않습니다.

### ISSUE THREAD

**Issue by dsdstudio** [okjsp/okky#108]
안녕하세요 

계정찾기기능을 통해 이메일쪽 링크로 비밀번호 변경 후 

로그인시 아래와 같은 오류가 나네요 확인 부탁 드립니다 :) 

![2016-05-19 2 46 38](https://cloud.githubusercontent.com/assets/539734/15369090/19f15736-1d6c-11e6-9661-61836cb3696a.png)

**Comment by 1angerhans** [comment]
늦게 확인드려서 죄송합니다. 혹시 계정문제는 아직 이신가요?

**Comment by dsdstudio** [comment]
@1angerhans 답변 감사합니다. 다시 시도해봤는데 제가 아이디가 아닌 이메일 주소를 넣어 발생한 문제였네요 ㅠㅠ
