### ISSUE TITLE
페이스북 로그인 후 405

### ISSUE THREAD

**Issue by lsh0032** [okjsp/okky#109]
![20160615_048](https://cloud.githubusercontent.com/assets/19940846/16064477/9bcf94b8-32dc-11e6-8e7b-b56f1250806e.jpg)

페북으로 로그인 클릭 하고 
리다이렉션 되다가 405가 발생합니다. 

다시 오키 주소만 치면 로그인 된 것으로 됩니다. 
(#(해쉬? 샵?)이 뭔가 잘라 먹었을까요??)

**Comment by 1angerhans** [comment]
ajax로 json 통신되는 url에 세션에 남아서 로그인후 해당 url로 리다이렉션 되는 오류네요. 
해당 오류는 다음 업데이트에서 수정하도록 하겠습니다. 감사합니다. :D

**Comment by 1angerhans** [comment]
#114 와 연관되어 있습니다.
