### ISSUE TITLE
회원가입시 인증메일이 오지 않습니다.

### ISSUE THREAD

**Issue by KittyKuma** [okjsp/okky#111]
live.co.kr 메일로 인증을 하려고 했는데 스팸함에도 없고 메일도 오지 않습니다.
혹시 다른 메일로 인증하거나 인증메일을 다시 받을 수 있는 방법이 있나요?

**Comment by 1angerhans** [comment]
btjung@okky.kr 로 이메일 주소 보내주시면 계정인증 진행해드리도록하겠습니다. 현재 ms쪽 서비스에서 블록당하고 있는데 원인 파악 중입니다.

**Comment by 1angerhans** [comment]
#113 와 연관되어 있습니다.
