### ISSUE TITLE
okky 사이트 github code clone url으로는 이클립스에서 프로젝트 생성 불가?!

### ISSUE THREAD

**Issue by gandhi546** [okjsp/okky#112]
저는 큭큭푸푸 라는 닉네임으로 오키에서 활동 중인 신입유저입니다.

현재 학원에서 spring을 배우며 웹사이트 프로젝트를 진행하며 오키 사이트를 벤치마킹한

it 행사 전문 커뮤니티를 구현하고 있습니다. 다들 디자인에 서투르고, jsp 모델2 개념을 이해하기도 벅차 오픈 소스를 참고해 프로젝트를 진행하려고 합니다.
하지만, github에서 크론 url를 통해 이클립스에서 임포트하려고 하니, 계속 프로젝트를 찾지 못하는 현상이 발생하고 있습니다. 

![이클립스에서 프로젝트를 찾지 못하는 모습](https://raw.githubusercontent.com/gandhi546/origin/master/image.png)

Grails 라는 프레임워크를 이클립스에서 임포트할 수 있는 플러그인을 다운로드하지 않아서 발생한 것 같아, GGTS를 다운로드 받아 okky.kr zip파일을 임포트하려고 했습니다. 30분 grails 환경설정 강의도 참고하여 2.4.5 버전으로 grails도 설치했구요.

![GRAILS에서 프로젝트를 찾지 못하는 모습](https://raw.githubusercontent.com/gandhi546/origin/master/image%20(1).png)

역시, 프로젝트를 찾지 못하는 현상이 발생했습니다.깃허브 okky/ okjsp-site 경로의 프로젝트는 크론 uri로 임포트하여 확인했고, 구 사이트 자료라고 판단했습니다. kenu님의 조언 부탁드립니다. 참고할 소스가 없으니 답답하여 이슈게시판에 문의드립니다.

그럼 글 줄이겠습니다.

*추신: 프로젝트 멤버가 확인한 결과 GRAILS에서 임포트 중에 에러가 발생하며 임포트가 중지된다고 합니다.

**Comment by 1angerhans** [comment]
해당 소스는 이클립스 프로젝트가 아니라 임포트 프로젝트를 하시면 안되고 프로젝트를 새로 생성하셔야 합니다.
그리고 'GRAILS에서 임포트 중에 에러가 발생하며 임포트가 중지' 에 대한 내용은 좀 더 설명이 필요한 것 같습니다. 
grails에 import 라는게 정확히 어떤걸 말씀하시는거죠? grails > ggts 를 말씀하시는건가요?

**Comment by kenu** [comment]
1년 전에 공유했던 okky grails 개발환경 세팅입니다. 참고하세요.
https://www.youtube.com/watch?v=tZ9pP6mtSbo

**Comment by gandhi546** [comment]
@1angerhans 설명이 부족했네요. ggts로 import했었습니다. 
@kenu 님께서 시연영상 찍어주셨던 것 보고 했었는데, 놓친 부분이 있었네요.
 
프로젝트 팀원의 도움으로 무사히 ggts에서 import할 수 있었는데요. 제가 놓친 부분을 말씀드립니다.
kenu님 영상에서 제가 놓친 부분은 path 설정한 파일이 'program files' 폴더 아래에 있었다는 점입니다. cmd창에서 'grails'를 입력할 경우, error가 발생했습니다. program files 폴더명에 공백이 포함되어 grails 경로를 읽지 못하는 것이었습니다.  'C:\program files\Java\grails-2.4.5'경로를 'C:\Java\grails-2.4.5'으로 변경하니 무사히 import했습니다. 

빠른 답변으로 소통해주셔서 감사합니다.


![무사히 프로젝트를 compile하는 모습^^]
(https://raw.githubusercontent.com/gandhi546/origin/master/completed.PNG)
