### ISSUE TITLE
okky 에서 쓰고있는 wysiwyg(editor) 을 알수 있나요?

### ISSUE THREAD

**Issue by wdvvgy** [okjsp/okky#118]
okky 에서 사용되는 wysiwyg 을 사용하고 싶은데..

혹시 정보를 얻을 수 있을까요?

코드 선택 하는것이 너무 마음에 들어서요..

**Comment by 1angerhans** [comment]
http://summernote.org 라는 에디터를 사용합니다.

그런데 코드 선택 부분은 제가 커스터마이징 하여 추가 한 것입니다.

코드 뷰는 http://prismjs.com 를 사용했습니다.
