### ISSUE TITLE
글 등록 후, 수정상태에서 태그등록 후, 글을 저장하면 에러 발생합니다.

### ISSUE THREAD

**Issue by s3ongsil** [okjsp/okky#119]
에러 메세지 
An error has occurred

태그를 미등록 하여 글을 수정하여 태그 작성 후 저장을 하면 위와 같은 에러메세지가 발생합니다.
당연히 글 수정(태그등록)도 안되구요

사용환경 : 윈도우10, 파이어폭스48.0.2

**Comment by 1angerhans** [comment]
오류 수정됐습니다.
