### ISSUE TITLE
댓글이 있는글은 삭제할수 있는 방법이 없을까요??

### ISSUE THREAD

**Issue by ChoiYongWook** [okjsp/okky#129]
댓글이 있는 글은 삭제해야하는 경우가 있을것 같은데
삭제는 어떻게 해야할까요???

**Comment by 1angerhans** [comment]
기본적으로는 삭제가 불가능합니다.
만약 개인정보보호등의 이유로 삭제를 원하시면 btjung@okky.kr 로 삭제 요청 주시기 바랍니다.
요청 주실 때 메일은 가입하신 메일로 보내 주세요.
