### ISSUE TITLE
facebook 로그인 및 회원가입 불가

### ISSUE THREAD

**Issue by hsol** [okjsp/okky#131]
특정 사용자에게만 그런것인지는 모르겠는데
molmoty@gmail.com 계정으로 로그인 불가합니다. (아무처리 없이 리로딩됩니다.)

**Comment by 1angerhans** [comment]
해당 이메일로 가입한 계정이 disabled 되있는 상태이네요. 혹시 마지막으로 계정 사용하신게 언제인가요?
