### ISSUE TITLE
'구직'메뉴에 안들어 가져요.

### ISSUE THREAD

**Issue by yousik** [okjsp/okky#138]
'구직'메뉴에 안들어가져요.
로긴전에 선택하면 로그인 하라고 하고..
로그인하고 선택하면 'Sorry, you're not authorized to view this page.' 이라는 메세지만 뜨네요.

**Comment by 1angerhans** [comment]
카테고리 셋팅이 잘못되있었네요. 수정되었습니다.

**Comment by yousik** [comment]
우와…연휴인데…이렇게…..^^

고맙습니다.

올 한해 대박 나시길 빕니다.
