### ISSUE TITLE
https 적용 후 facebook login failure

### ISSUE THREAD

**Issue by kenu** [okjsp/okky#143]
https://okky.kr/article/382568
리포트 보고 테스트해 보니 failure로 갑니다.

<img width="793" alt="2017-03-28 5 43 14" src="https://cloud.githubusercontent.com/assets/718691/24396623/c716c70c-13de-11e7-8767-7d6189111496.png">

**Comment by 1angerhans** [comment]
어제 확인해봤는데, 아직 원인은 파악 못했습니다. ㅠㅠ
오늘 더 확인 해볼께요.

**Comment by kenu** [comment]
https://gs.saro.me/#!m=elec&jn=885
슛돌이 님이 알려주신 링크입니다.
https://okky.kr/article/382568?note=1207258
