### ISSUE TITLE
구직란 게시판 최상단에 홍보글을 올리고 싶은데요...   가격이 어떻게 되나요?

### ISSUE THREAD

**Issue by kimsungnama** [okjsp/okky#145]
현재 올라와 있는 글처럼   홍보글을 올리고 싶습니다.     
 
아래는  현재 올라와 있는 공지글 입니다.  ----
[정규직] 요즘 너무 뜨거우신 모발 개발자분을 찾습니다용~ 
--------------------------------------------------------
korealancer@naver.com   메일 부탁 드립니다.

수고하세요

**Comment by kenu** [comment]
ad@okky.kr 로 메일을 보내주시면 됩니다.
