### ISSUE TITLE
비밀번호 변경후 로그인이 되지 않습니다.

### ISSUE THREAD

**Issue by arosmile** [okjsp/okky#152]
로그인 하기 힘드네요. arosmile@naver.com 이구요 계정 찾기로 이메일 받아서 변경 후 변경이 안된건지 뭔지 비밀번호가 틀렸다고 합니다. 잘못쳤나 싶어서 세번이나 비밀번호 변경 절차를 밟아 정확히 확인했는데도 그러네요. 구글로 로그인은 로그인한거지 거기에서 왜 더 회원가입 절차를 밟아야 하는지 모르겠구요. 그건 로그인이 아니라 구글로 회원가입이라고 정확히 명시해주셨으면 좋겠습니다. 이미 회원 가입이 되어있늗네 또 가입하기 싫으니 빨리 해결해주시기 바랍니다.

**Comment by 1angerhans** [comment]
확인보았는데 어떤 문제인지 확인이 안되네요. 혹시 괜찮으시면 제가 임의로 비밀번호를 설정해서 확인해봐도 될까요?

**Comment by arosmile** [comment]
헐 ㅜ 지금확인했네요.. 바꿔서 확인 해보셔도 됩니다.

2017년 7월 6일 오후 7:41, 정병태 <notifications@github.com>님이 작성:
