### ISSUE TITLE
글 작성 500에러

### ISSUE THREAD

**Issue by dehypnosis** [okjsp/okky#156]
댓글 작성은 됩니다만, 어떤 게시판이던 글이 작성이 안되네요.
별다른 에러메세지는 없구요.
무슨 에러죠?
에러가 아니라면 제가 밴을 당한건가요?

---

An error has occurred

About OKKY | 개인정보보호 | Contact | Facebook | Github v0.11.0 
@ 2017 eBrain Management

**Comment by 1angerhans** [comment]
btjung@okky.kr 로 아이디/닉네임 알려주시면 계정 확인 해보겠습니다.
