### ISSUE TITLE
Q&A 이용관련하여 의견을 올립니다.

### ISSUE THREAD

**Issue by richinhim** [okjsp/okky#157]
옥히가 개발자 커뮤니티이다 보니 질문 사항이 많이 생기면 Q&A에 질문을 올리는데.
해당 질문에 대한 해결여부가 표시가 되었으면 좋겠다는 생각이 방금 떠올랐습니다.

예를 들어) 문제를 작성자가 올립니다. 그리고 답변이 올라옵니다. 작성자가 해결이 되면.
해결되었다는 버튼 또는 다른 액션이 가능하면 어떨까하는 생각이 들었습니다.
그래서 검색했을때 해결여부를  확인할수 있으면 편리하겠다는 생각입니다.
진행중 또는 해결완료 이런 표시가 되었으면 합니다.
감사합니다.

**Comment by kwamuki** [comment]
현재는 질문자가 답변을 채택할 경우 리스트 화면에서 녹색으로 표시됩니다. 
의견 감사합니다.

**Comment by richinhim** [comment]
감사합니다.^^
