### ISSUE TITLE
비밀번호 생성규칙좀 알려주세요.

### ISSUE THREAD

**Issue by goopers** [okjsp/okky#159]
비밀번호를 찾을려 하는데 어떤 조합의 비밀번호를 넣어야 하는지요?
수십번은 다른 것을 조합하여 넣어도 변경되지를 않네요.
메일은 gooper@gooper.com입니다.
수고하세요.

**Comment by 1angerhans** [comment]
비밀번호 정규식에 오류가 있었습니다. 현재 수정되어 반영하였구요. 숫자+문자 조합으로 생성가능합니다.

**Comment by espozbob** [comment]
@1angerhans 처리된 이슈는 close하면 좋을 것 같습니다.
