### ISSUE TITLE
상단 배너 광고 문제

### ISSUE THREAD

**Issue by zepinos** [okjsp/okky#160]
광고 때문에 모바일에서 가로 스크롤이 생깁니다.

![screenshot_2017-10-30-16-22-23](https://user-images.githubusercontent.com/6926839/32158998-c7a462ce-bd8e-11e7-8a15-b6dc1cd6e5eb.jpg)

아울러, 알림창이 광고에 가려집니다.

![screenshot_2017-10-30-16-22-32](https://user-images.githubusercontent.com/6926839/32158988-bdce2adc-bd8e-11e7-84cb-beedae6acbca.jpg)

**Comment by kwamuki** [comment]
Tag 형태의 광고라서 모바일 대응이 안되었습니다.
모바일에서는 해당 광고가 나타나지 않도록 조치했습니다.
