### ISSUE TITLE
SNS 회원가입시 이메일 필수입력 오류

### ISSUE THREAD

**Issue by espozbob** [okjsp/okky#161]
* 증상
1. 로그인
1. 페이스북 로그인 선택 - 페이스북 로그인
1. SNS로 회원가입 화면 이동
1. 회원가입>닉네임 입력, 로봇아님 체크
1. 회원가입 클릭
1. "이메일"은 필수입력입니다. 에러 뜨고 회원 가입 안됨

* 스샷
![2017-11-17 3 38 11](https://user-images.githubusercontent.com/2732120/32933793-1cde6e10-cbae-11e7-9f94-a825450e4d8e.png)

**Comment by espozbob** [comment]
#130 , #88  문제 동일증상으로 판단 됨

**Comment by espozbob** [comment]
> email 권한을 요청하는 경우에도 이메일 주소를 받는다는 보장은 없습니다. 예를 들어, 이메일 주소 대신 전화번호를 사용하여 Facebook에 가입한 경우 이메일 필드는 비워둘 수 있습니다.

https://developers.facebook.com/docs/facebook-login/permissions#reference-email

**Comment by espozbob** [comment]
## 처리방안
1. 이메일 인증을 통한 계정활성화로 인해 전화번호만으로 가입한 사용자는 이메일을 입력하도록 readonly를 삭제한다.
2. SNS 인증 가입자에게는 이메일 필드 누락과 이메일 인증을 생략한다.

**Comment by 1angerhans** [comment]
이메일 필드 readonly 삭제 되었습니다.
