### ISSUE TITLE
아이폰 모바일로 글 쓸때 개행시 오류 문제

### ISSUE THREAD

**Issue by espozbob** [okjsp/okky#163]
* 증상
1. 아이폰에서 크롬 또는 사파리에서 오키접속 후 로그인
1. Q&A 메뉴에서 글쓰기 버튼 클릭
1. 아이폰 사파리에서 다음과 같은 증상이 나타납니다.
```
//아이폰 사파리에서 다음과 같이 입력합니다

반갑습니다
오랜만입니다

//위와 같이 입력하면 다음과 같이 나타납니다

반갑습니다다오랜만입니다

//'반갑습니다'를 입력후 줄바꿈을 하면 첫줄의 마지막과 두번째줄의 첫글자인 '다', '오'가 붙어버리면서
 '다다오'와 같이 표현되는 버그가 존재합니다.
```

**Comment by kwamuki** [comment]
@espozbob 단축키를 사용하지 못하면, 문단 스타일 적용(정열)은 버튼이 없어서 사용할 수 없네요. 문단 스타일 부분의 버튼이 노출되면 좋겠습니다. :smile:

**Comment by kwamuki** [comment]
@espozbob 모바일에서만 적용 되는 것으로 수정했습니다. #164

**Comment by espozbob** [comment]
@kwamuki 그럼 모바일에서는 문단 스타일 적용은 계속 안되는건가요?

**Comment by kwamuki** [comment]
네, @espozbob 님께서 모바일에서 수정할 수 있는 버튼 넣어주셔도 되고요 😄
