### ISSUE TITLE
글쓰기 작성시 tag 지정은 필수 입력 사항으로 수정

### ISSUE THREAD

**Issue by kwamuki** [okjsp/okky#17]
모든 게시판 글쓰기 작성시 tag 지정은 필수 입력 사항으로 수정

- 글쓰기
- tag 미 입력 후 글쓰기 완료하면 "tag를 입력해 주세요." 표시
- 모든 게시판에 적용

**Comment by 1angerhans** [comment]
Tag 필수 입력 카테고리와 아닌 카테고리를 구분할 필요가 있을듯 합니다.
Tag 자체가 파편화되는것을 막는것도 고민해봐야 할듯.

**Comment by yongbam** [comment]
태그가 필수 입력이면 너무 파편화 되지 않을 까 싶어요. 많이 쓰는 태그를 추천해주면 좋겠어요

**Comment by kwamuki** [comment]
- 네, 우선 Q&A 부분은 필수 입력이 필요할 듯 싶습니다.
- 나머지 부분에 대해서는 tag 필수를 고민해 봐야 할 것 같습니다.
- @yongbam 태크 추천기능이 필요하지만 기술적으로 정책적으로 고려할 사항들이 많은 것 같습니다. 퍼포먼스도 고려해야 하고요. :smile:
