### ISSUE TITLE
목록보기가 왜 없는건가요?

### ISSUE THREAD

**Issue by 3dsoft** [okjsp/okky#174]
PC도 그렇고 모바일도 그렇고 특정 글을 클릭해서 볼경우, 목록보기가 없어서 항상 뒤로가기나 왼쪽 메뉴를 클릭해야해서 너무 불편한데, 게시판의 기본이라고도 할 수 있는 목록보기 버튼을 넣지 않은 이유가 뭔가요?

**Comment by 1angerhans** [comment]
뒤로가기 버튼 누르는게 게시물 길이에 따라 위치가 바뀌는 목록 버튼 찾아서 누르는거보다 진짜로 불편하신건가요?
우선 저는 목록버튼이 들어가는 순간 상세페이지 유입 이전 페이지의 상태까지 유지시켜야되는 복잡도에 비해 진짜로 필요한 기능인지 고민해 볼 필요 있다고 생각합니다. 만약 뒤로가기 기능이 제대로 작동 안하는 경우 (예 : 댓글을 작성후 뒤로 가기하면 입력폼으로 돌아감) 같은 경우는 목록버튼을 다는것 보다는 해당 문제를 해결하는게 더 낫다고 생각 합니다.

그리고 지금 쓰신 깃헙 이슈에 목록 버튼이 있는지 확인해보세요.
'게시판에 기본기능' 이라는 것이 관습적으로 그려온 화면설계에 스스로 적응한 것 아닌지 고민도 해보실 필요 있다고 보입니다. 

저는 말씀하신 '게시판의 기본기능' 을 생각하고 만들지 않았구요, 느리지만 하나씩 구현 중입니다.

만약 그래도 목록 보기 버튼이 필요하시다면 풀리퀘스트 부탁드립니다. 구현 수준에 따라 사용가능한 수준이면 머지하겠습니다.

의견 감사합니다.

**Comment by 3dsoft** [comment]
목록보기 기능이 없어서 불편하게 저 혼자이고, 개발자분 역시 구현이 어렵고 불필요한 기능이라 생각되신다면 굳이 구현할 필요는 없어보입니다. 
수고하세요.
