### ISSUE TITLE
이메일 인증링크 만료시 재발송이 불가

### ISSUE THREAD

**Issue by deadlykitten-dev** [okjsp/okky#176]
이메일에 첨부된 인증링크가 만료되는 현상이 발생하였는데 추가 인증요청이 불가하고 또 해당 메일이 중복되어 재가입도 안되는 현상이 있습니다. 로그인이 되지않아 QnA도 불가하여 부득불 깃헙 이슈에 해당 현상을 남깁니다.

**Comment by 1angerhans** [comment]
로그인 하단 > 계정 찾기로 비밀번호 변경 링크를 받으실 수 있습니다. 해당 링크로 비밀번호 입력후 사용 가능합니다.

**Comment by deadlykitten-dev** [comment]
인증완료 되었네요 감사합니다
