### ISSUE TITLE
탈퇴후 가입했는데 가입이 안되네요..

### ISSUE THREAD

**Issue by ahnjehoon** [okjsp/okky#177]
6개월 지났는데 가입이 안되네요..

페이스북 계정이였습니다.

**Comment by 1angerhans** [comment]
탈퇴해도 페북계정이 삭제가 안되었었나보네요.
btjung@okky.kr 로 아이디 보내주시면 재가입 가능하도록 처리하겠습니다.

**Comment by ahnjehoon** [comment]
ahnjehoon@naver.com 입니다
감사합니다
-----Original Message-----

**Comment by 1angerhans** [comment]
초기화되었습니다. 재가입 부탁드립니다.
