### ISSUE TITLE
구글 로그인이 안됩니다.

### ISSUE THREAD

**Issue by SONJONGWOOK** [okjsp/okky#179]
2일정도 계속 시도하고있습니다. 

로그인 시도하면
An error has occurred
[Go to Main] 
라는 메시지가 뜹니다. 

계속 시도해볼텐데요 되엇을땐 이글을 수정하겠습니다.

**Comment by antop-dev** [comment]
네 안되고 있습니다. ㅠㅠ

**Comment by 1angerhans** [comment]
연동 스펙이 바뀐거 같네요. 현재 확인중입니다.

**Comment by SONJONGWOOK** [comment]
감사합니다
