### ISSUE TITLE
nginx 설정 제안

### ISSUE THREAD

**Issue by salesyan** [okjsp/okky#181]
- server_tokens off; 
항목 적용하시는 것을 추천합니다. 현재 nginx 버전이 보이더라고요.

- ssl 적용 중이면 http2까지 적용하는건 어떨까 싶습니다.
http2 indicator로 확인해보면 아직 1.1로 동작하는걸로 보입니다.
(성능이 얼마나 차이는 날지 모르겠지만요)

conf 파일을 볼 수가 없는 터라 이 정도 밖에는 말씀드릴 수가 없네요.

**Comment by 1angerhans** [comment]
제안주신데로 적용하였습니다.
확인해보니 사파리에서는 http2 로 나오고 크롬에서는 1.1 로 나오네요;;

**Comment by salesyan** [comment]
firefox도 1.1로 나오네요.
저도 let's encrypt 인증서 사용하는 사이트 있는데,
특별히 옵션 같은거 안 줬는데요 2.0으로 나오는데 좀 이상하네요^^;
