### ISSUE TITLE
구글 로그인시 not authorized 페이지 뜨는문제

### ISSUE THREAD

**Issue by quodvide** [okjsp/okky#182]
아무것도 안누르고 크롬환경에서 구글 로그인만하면 not authorized 페이지가 뜹니다. 다른 게시판으로 접속하여 정상이용 가능하나 로그인시 저화면이 뜨는건문제가 있는것같아서 이슈올립니다. 

<img width="1069" alt="2018-11-13 7 06 07" src="https://user-images.githubusercontent.com/13764108/48406346-92834100-e777-11e8-9821-19a07dffa18d.png">

**Comment by 1angerhans** [comment]
서버에서 구글과 통신시 timeout이 발생하면서 나는 오류입니다.
지금 의심되는 네임서버 아이피를 변경하여 적용하였는데요.
혹시 계속 발생하는지 확인 부탁드립니다.

**Comment by quodvide** [comment]
오, 이제 안뜹니다 :D

정상 로그인되네요.
