### ISSUE TITLE
구글 로그인이 안됩니다.

### ISSUE THREAD

**Issue by inthej** [okjsp/okky#205]
이전부터 계속 시도하고 있습니다.

로그인 시도하면
An error has occurred
[Go to Main]
라는 메시지가 뜹니다.

계정: inthej12@gmail.com 입니다.
계속 시도해 볼 텐데요 되었을 땐 이 글을 수정하겠습니다.

**Comment by kwamuki** [comment]
@inthej , 
확인해보니 탈퇴하신 계정으로 나타납니다~

**Comment by inthej** [comment]
@kwamuki 답변 감사합니다.
탈퇴하면 재가입이 안된다는 내용을 인지하고 못하고
아이디 정리하는 과정에서 실수로 탈퇴한 거 같은데요.
재가입 가능하도록 조치 부탁드릴 수 있을까요?

해당 계정이 저의 메인 계정이라 가능하면 메인 계정으로 okky 사이트 이용하고 싶습니다.
좋은 정보 공유 및 커뮤니케이션 활성화에 도움 되는 유저가 되겠습니다.

**Comment by kwamuki** [comment]
@inthej , 탈퇴하신지 6개월 이상이신 것 같습니다.
그러면, 위 계정으로 재 가입이 되십니다.
혹시 재가입 해보시고 안되면, 다시 말씀해주세요~ 👍

**Comment by inthej** [comment]
@kwamuki 네. 재가입 시도 해보았는데요. 동일 증상 발생되어 가입이 안됩니다. ㅠ

**Comment by kwamuki** [comment]
@inthej , 지금 다시 가입 부탁드립니다. 
기존 계정을 삭제했습니다.

**Comment by inthej** [comment]
@kwamuki 가입 완료하였습니다. 감사합니다!
