### ISSUE TITLE
사이트 접속이 안되는듯합니다

### ISSUE THREAD

**Issue by yangseungin** [okjsp/okky#223]
![image](https://user-images.githubusercontent.com/24931203/145494090-fc3bac0f-f7b4-4013-b6bb-3e7ff433bb71.png)

**Comment by ehaakdl** [comment]
저도 비슷한 에러가 납니다.
![image](https://user-images.githubusercontent.com/6407466/147877685-9bc96d60-feda-46bb-a66b-c31311906d0a.png)

**Comment by yangseungin** [comment]
해결된듯해서 내리겠습니다
