### ISSUE TITLE
코드블럭에서 라인 숫자 표시문제

### ISSUE THREAD

**Issue by yongbam** [okjsp/okky#26]
분명 체크하고 코드블럭 생성 후 소스를 붙여넣었는데 게시 후 숫자가 없어요

**Comment by kwamuki** [comment]
코드블럭 부분 확인해 보겠습니다. :smile:

**Comment by 1angerhans** [comment]
코드 하일라이트가 정상적으로 작동안하는 문제때문인것 같습니다.
