### ISSUE TITLE
okjsp.net, okjsp.pe.kr 루트 페이지 접속시 포워딩

### ISSUE THREAD

**Issue by kenu** [okjsp/okky#29]
http://okjsp.net/  
http://okjsp.pe.kr  
접속시 
현재는 nginx 기본 페이지가 잘 나오고 있습니다.
:)

![2015-02-16 8 16 23](https://cloud.githubusercontent.com/assets/718691/6211014/bf7b0ccc-b618-11e4-82a9-10763c105d0a.png)

**Comment by kwamuki** [comment]
수정 했습니다. ^^
