### ISSUE TITLE
bot에 의한 crawling시 한글 문제

### ISSUE THREAD

**Issue by deokgonkim** [okjsp/okky#35]
실제로 bot으로 crawling하는 것은 아니지만 비슷한 동작방식입니다.

SiteBar라는 웹북마크 프로그램을 사용중입니다.
이 프로그램에서 OKKY주소를 가져와 추가할 때 한글이 제대로 표시되지 않습니다.

meta 태그에 문제가 있을 것이라 추정합니다.

재연은 http://my.sitebar.org/ 접속후 DEMO Bookmarks 아래에 RIGHT CLICK here to add your bookmark 같은 곳에서 '링크 추가' 선택한 후 OKKY의 article주소를 넣고, '링크정보 가져오기'를 누르면 한글 부분이 '?'문자로 표시됩니다.

**Comment by 1angerhans** [comment]
감사합니다. 현재 구글 크롤링에서 한글이 깨지는 문제가 있어서 찾고 있는 중이었습니다.
근데 아직까지 meta 나 charset 등 아무리 살펴봐도 정확한 원인을 찾지 못하고 있습니다.
혹시 의심되는 부분 있으시면 의견 부탁드리겠습니다.

**Comment by herblover** [comment]
음... curl 로 확인해 보니, Content-Language Header가 들어오고 있네요. 이 부분을 빼 보시는건 어떨까요? 보통 큰 문제 없는 부분인데, 서버에서 돌려주는 경우가 많지는 않아서(잘 안쓰는 Header 입니다.) 한번 확인해 보는 것도 좋을것 같습니다.

curl -I http://okky.kr 로 response header 확인이 가능합니다.

```
~/developments/labs/okky[master] » curl -I http://okky.kr
HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Wed, 25 Feb 2015 02:13:33 GMT
Content-Type: text/html;charset=UTF-8
Content-Length: 63686
Connection: keep-alive
Vary: Accept-Encoding
Content-Language: ko-KR
```
Devpia 는 다음과 같이 돌려주고 있네요.
```
~/developments/labs/okky[master] » curl -I http://devpia.com
HTTP/1.1 200 OK
Content-Length: 106
Content-Type: text/html
Last-Modified: Mon, 27 Sep 2010 04:31:33 GMT
Accept-Ranges: bytes
ETag: "a06159ddfc5dcb1:0"
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
Date: Wed, 25 Feb 2015 02:15:23 GMT
```
stackoverflow 는 다음과 같습니다.
```
~/developments/labs/okky[master] » curl -I http://stackoverflow.com
HTTP/1.1 200 OK
Cache-Control: public, no-cache="Set-Cookie", max-age=20
Content-Length: 237637
Content-Type: text/html; charset=utf-8
Expires: Wed, 25 Feb 2015 02:16:01 GMT
Last-Modified: Wed, 25 Feb 2015 02:15:01 GMT
Vary: *
X-Frame-Options: SAMEORIGIN
X-Request-Guid: 942cd527-118f-44ef-a202-629088292662
Set-Cookie: prov=b6ed0b23-fcbe-433b-869b-a8ca35e8e06c; domain=.stackoverflow.com; expires=Fri, 01-Jan-2055 00:00:00 GMT; path=/; HttpOnly
Date: Wed, 25 Feb 2015 02:15:40 GMT
```
Naver 도 대충 비슷하고요.
```
~/developments/labs/okky[master] » curl -I http://www.naver.com
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/html; charset=UTF-8
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
P3P: CP="CAO DSP CURa ADMa TAIa PSAa OUR LAW STP PHY ONL UNI PUR FIN COM NAV INT DEM STA PRE"
X-Frame-Options: SAMEORIGIN
Date: Wed, 25 Feb 2015 02:18:55 GMT
Content-Length: 0
Connection: keep-alive
```
테스트 한 여러 사이트 중, 다음은 Content-Language를 전송해 주고 있는데, 신기하게도 en-US로 보내 줍니다.
```
~/developments/labs/okky[master] » curl -I http://www.daum.net
HTTP/1.1 200 OK
Date: Wed, 25 Feb 2015 02:19:05 GMT
X-UA-Compatible: IE=10
Expires: Sat, 01, Jan 1970 22:00:00 GMT
Pragma: no-cache
Cache-Control: no-cache, no-store, must-revalidate
P3P: CP="ALL DSP COR MON LAW IVDi HIS IVAi DELi SAMi OUR LEG PHY UNI ONL DEM STA INT NAV PUR FIN OTC GOV"
Content-Type: text/html;charset=UTF-8
Content-Language: en-US
Content-Length: 163839
Vary: Accept-Encoding
X-UA-Device-Type: pc
Connection: close
```
혹시 모르니, Content-Language 부분도 한번 확인해 보시는것도 좋을꺼 같아요~

**Comment by kwamuki** [comment]
@herblover 감사합니다. ^^

**Comment by 1angerhans** [comment]
@herblover 제가 Content-Langage 를 설정으로 넣어준건 아니고 grails 어디선가 자동으로 넣어주고 있는거 같은데요. 인덱스와 게시물 페이지도 헤더가 미묘하게 틀린것도 의심스럽구요. 쓰다보니 캐시컨트롤헤더 플러그인이 의심스럽네요!!!!!
역시 개발자는 소통을해야돼....감사합니다 ㅋㅋㅋ

**Comment by 1angerhans** [comment]
Controller에서 respond 메소드 사용시 Grails 버그 인것으로 확인됐습니다.

http://stackoverflow.com/questions/26992902/grails-respond-method-outputs-html-content-with-charset-iso-8859-1

https://jira.grails.org/browse/GRAILS-11830

2.4.5에 수정된다는 소식이...쿨럭..

우선 강제 설정으로 처리 하였습니다.

**Comment by deokgonkim** [comment]
뭐가 바뀐 건진 모르겠습니다만. SiteBar에서 현재 잘 되네요.
