### ISSUE TITLE
댓글 순서

### ISSUE THREAD

**Issue by zepinos** [okjsp/okky#43]
http://okky.kr/article/272724

위 글을 보시면 댓글 단 순서대로 글이 나오질 않습니다.

![okky_2015-02-25_15-23-35](https://cloud.githubusercontent.com/assets/6926839/6365978/50e1bf0e-bd02-11e4-8915-ea388ca21534.png)

**Comment by 1angerhans** [comment]
우선 Q&A 에서는 선택된답변/추천/작성시간 순으로 sorting 됩니다.
기존 대화방식의 질답형태에는 맞지 않아 생기는 문제인데요. 
현재 보안책으로 답변에 대한 의견 주고받기 기능을 추가할 계획입니다.
답변의 의견 기능이 추가되면 Q&A에서는 답변을 한번만 달 수 있도록 하고, 답변자체를 수정하는 방식으로 유도할 계획입니다.

**Comment by zepinos** [comment]
선택된 답변이라는게 있었군요.

그런데 선택된 답변을 제일 위에 보여주고, 아래 원래 위치에 해당하는 곳에 선택된 답변이라고 칸을 유지시키는게 혼동을 줄이는 방법 같습니다. 아울러...추천이 많은 것은 배경색을 달리 보여준다는 식으로 하는게 좋을 것 같습니다. 순서가 바뀌어버리니 이상하네요.

역시나 댓글 소팅은 작성 순서대로가 가장 좋을 것 같아요. ^^;;;

**Comment by 1angerhans** [comment]
네. 저도 현재 상태에서는 이상한거 같네요.
그럼 우선 의견기능이 생기기전까지는 작성순서대로 sorting 으로 바꿀지 여부를 논의해보도록하겠습니다.
의견 감사드립니다.
