### ISSUE TITLE
로그인후에 okky.kr/bbs?act=FIRST_MAIN로 이동합니다.

### ISSUE THREAD

**Issue by TaeSeong** [okjsp/okky#46]
안녕하세요.

매번 그런거같지는 않은데 로그인후에 

http://okky.kr/bbs?act=FIRST_MAIN 로 리다이렉트되는 경우가 있습니다.

소스상에 예전 경로가 남아있는건지..

간헐적으로 발생하는것 같네요

**Comment by 1angerhans** [comment]
해당 문제는 이전 메인 url인 http://www.okjsp.net/bbs?act=FIRST_MAIN 로 접속할 경우 발생합니다.
/bbs 에 대한 redirection 처리를 추가해놓겠습니다.
