### ISSUE TITLE
에디터에서 복사+붙여넣기가 안됩니다

### ISSUE THREAD

**Issue by TaeSeong** [okjsp/okky#47]
![2015-02-27 11 20 55](https://cloud.githubusercontent.com/assets/7597961/6406343/c6d7c886-be72-11e4-91ba-9f992fccd613.png)

안녕하세요.

댓글 입력시에만 확인해봤는데

제가 맥환경이라 그런지 모르겠으나 에디터에서 복사 + 붙여넣기가 작동하지를 않네요

확인 부탁드립니다

**Comment by 1angerhans** [comment]
현재 확인 한 바로 붙여넣기 작동은 잘 되는 듯한데요. 어떤 브라우저를 사용중이신가요?

**Comment by TaeSeong** [comment]
지금 확인해보니 잘되네요.
환경 문제였던거 같네요.
이슈 클로즈 하겠습니다~!
