### ISSUE TITLE
새 글 쓰기 관련해서..

### ISSUE THREAD

**Issue by Sepis** [okjsp/okky#48]
안녕하세요~
새 글 쓰기 도중에 몇가지 눈에 띄어 남깁니다.

1. 좌측 서브 메뉴가 선택되어있는 상태에서 새 글 쓰기를 하면 해당 카테고리가 선택되어있지 않음.

2. 공지사항을 선택 후, 글쓰기 시 등록됨. 
   - 공지사항은 권한 외에 사용자 등록불가 필요할 듯.

**Comment by 1angerhans** [comment]
1. 글 작성시 자신이 작성할 카테고리를 다시한번 확인하는 차원에서 자동선택은 되지 않게 하였습니다.
이전 사이트에서 다른 게시판에 작성된 글을 옮기는 것도 운영자의 일중에 하나였거든요.

2. 공지사항 글쓰기는 굳이 막지 않았습니다. 자발적 필터링이 이루어진다면 굳이 필요없는 제한사항이라고 생각 되기 때문입니다. 공지사항 게시판의 의미가 퇴색되는 날에 해당권한 처리를 하겠습니다. 크지는 않겠지만 이것이 자발적 필터링의 지표 역활같은걸 해줄 수 있을것이라고 생각합니다.
같은 의미로 컬럼도 원래 취지는 운영자님이 컬럼을 기고 받아 작성하는 게시판이지만 현재는 막지 않았습니다.
