### ISSUE TITLE
화면이 깨져요.

### ISSUE THREAD

**Issue by bbjjy** [okjsp/okky#49]
제 브라우져는 익스플로러 9 입니다.
화면이 심하게 깨져서 제대로 사용이 불가능하네요
호환성 보기를 해도 깨져요

**Comment by 1angerhans** [comment]
저는 정상적으로 나오는데, 혹시 캡쳐화면을 볼 수 있을까요?

**Comment by bbjjy** [comment]
화면

**Comment by bbjjy** [comment]
github에 사진 올리고 싶었는데 안올라가져서
 
화면 깨진모습 첨부해서 보냅니다

 
블로그서명안녕블로그
안녕하세요.
-----Original Message-----

**Comment by bbjjy** [comment]
![okky](https://cloud.githubusercontent.com/assets/11225926/6548527/739a70fe-c63f-11e4-9729-90ffb18a5d5d.jpg)

**Comment by 1angerhans** [comment]
IE7 에서 보는 화면하고 동일하네요. 
어떤 특정 설정으로 강제로 호환성보기가 작동되는걸로 보여지는데요.
브라우저 우측 설정 메뉴에서 '호환성 보기 설정' 에 okky.kr 이 등록되어있는지 확인 부탁드립니다.

**Comment by bbjjy** [comment]
호환성 보기 설정 목록에는 없습니다.
