### ISSUE TITLE
덧글 쓰기 및 링크 안됨현상

### ISSUE THREAD

**Issue by unanger** [okjsp/okky#50]
환경은 IE8(버젼8.0.7601) 이구요.. TRUSZOEN 으로 망분리 시스템을 통해서 오키에 접속 합니다. 
그외 별 특이사항은 없구요.. 

지금 제가 확인한 이슈는 모든글에 덧글을 쓰는건 되지만 옆에 등록 버튼에 마우스 업 했을때 안된다는 사선? 표시가 뜹니다 .
그러니깐 글쓰기는 가능하나 등록버튼이 안먹네요.. 

두번째는 사소하긴 하나. 정보수정 링크가 안먹네요.. 그래서 그냥 URL 복사해서 정보 수정 했어요..

**Comment by 1angerhans** [comment]
해당 내용 수정됬습니다. 혹시 다시 확인 가능하신가요?
