### ISSUE TITLE
새로운 OKJSP 불편점들

### ISSUE THREAD

**Issue by jerong** [okjsp/okky#53]
새로꾸민 okjsp 도무지 보기가 답답합니다..
요즘 사람들 UI 는 한눈에 쉽게 들어오는 것을 원하던데

폰트가 크고 두꺼워서 사이트 움직임이 둔탁하고,
한눈에 들어오지 않고, 도무지 뭐가 뭔지 모겠네요...

색은 왜이리 칙칙한지...phpschool  모방 느낌도 들고
거기는 폰트크기라도 작아서 페이지가 한눈에 가볍게 들오는데
여기는 줄간격이 넓고, 글자가 커서  스크롤을 자꾸 해야만 한다. 노안용 사이트인듯하네요...

거기다 왼편 메뉴도 알듯말듯 아이콘 덜렁 하나.(수수께끼 같은 아이콘들...허이구).
옆으로퍼지는2단 메뉴는 MS 사 원노트인가에서 구현해서 느리고 답답해서 다들 싫어하는 구성인듯한데요..

여러사람이 기획한거 일텐데...내눈이 이상한가봅니다...
뽐뿌구성등 대형 커뮤니티 참조좀 해주시면 어덜까용...

결론:  복잡한 세상, 어렵게 만들지 말시고  쉽게 좀 보고 사용할수 있게 만들어주세용...
          개발을 위한 사이트가 아니라 이용자를 위한 사이트를 만들어주세요

**Comment by 1angerhans** [comment]
네 의견 감사합니다.
사이트 디자인에 대해서는 여유가 될때마다 조금씩 개선해나갈 예정입니다. 
bs3 를 커스터마이징 없이 이용하다보니 전체적으로 글씨들이크고 오브젝트들이 조금 산만한 부분은 분명 있습니다.
혼자 하다보니 시간이 많지 않아 그런부분들은 계속 뒤로 밀리네요.

----
그리고 저도 부탁드리고 싶은점이 있는데요.

현재 OKKY 사이트가 만들어진 히스토리와, Github에 소스를 공개하고 여기 Issues 까지 사이트에 링크를 걸어놓으걸 보셨으면 아실꺼라 믿고 구구절절 설명드리진 않겠습니다. 
변경하고 싶으신 방향이 있으시면 앞으로도 계속 제시해주시고, 소스도 pull request 해주신다면 jerong님이 원하시는 사이트로 변신도 가능합니다.

다만 앞으로 의견을 주실때에는 이죽거림은 조금 빼주시고, 의견은 좀 더 구체적으로 부탁드립니다.
싫은점에대한 나열보다는, 개선방향과 그에 대한 조금 더 구체적인 이유를 적어주신다면 더욱 도움이 되겠죠.
특히 의견을 주신 디자인/UI 에 관련된 부분은 객관적이기는 쉽지 않고, 호불호를 말하기는 쉬워서 커뮤니케이션 시에도 더욱 섬세하고 이성적인 커뮤니케이션이 요구되는 부분입니다.

jerong 님께서 이곳에 글을 쓰셨다는 것은 이미 okky 의 contributor 로 참여하셨다는 의미이고, 
'개발을 위한 사이트가 아니라 이용자를 위한 사이트' 를 만들 수 있는 주체자라는 의미 입니다.
앞으로도 좋은 의견 부탁드리겠습니다.
