### ISSUE TITLE
모바일에서 글 볼 때 시간 표시

### ISSUE THREAD

**Issue by kenu** [okjsp/okky#55]
https://www.facebook.com/photo.php?fbid=916234415096086&set=a.135718299814372.41443.100001286086855&type=1&theater

**Comment by 1angerhans** [comment]
현재 시간표시 잘 되고 있는데 캡쳐를 할 때 윗부분을 가린채 한듯 합니다.
![lafj](https://cloud.githubusercontent.com/assets/2331803/6651926/6942f370-ca9e-11e4-8d94-a261d2ad8caf.jpg)

**Comment by kenu** [comment]
확인 감사합니다.
