### ISSUE TITLE
본문내의 링크클릭시 무조건 새창으로 뜨게 ...

### ISSUE THREAD

**Issue by ssoju** [okjsp/okky#63]
본문내에 있는 링크를 클릭할때 무조건 새창으로 뜨게 하는건 문제가 있을는지요..^^;;

이를테면,
$(document).on('click', '.content-text a:not([blank=target])', function(e){
    window.open(this.href); 
});

**Comment by 1angerhans** [comment]
본문의 링크를 강제적으로 새창을 띄워야 되는 이유는 무엇인가요?

**Comment by ssoju** [comment]
링크를 클릭하면 okky.kr에서 벗어나니까 다시 url를 입력하거나
back버튼을 몇번씩 눌러서 돌아오는게 불편하다는 생각이 들어서..
대부분 유저들이 okky.kr 에 머뮬면서 새창으로 해당링크에 들어가고자 하지 않을까 싶은..^^;
..(머 이것은 지극히 개인적인 생각입니다...)

**Comment by 1angerhans** [comment]
사실 저도 이부분을 작업하면서 나름대로는 많이 고민을 했구요. 
그부분에 대한 얘기를 함께 나눌 수 있는 이슈를 던져주셔서 참 감사드립니다.

우선 제 취향과 제가 검토했던 부분에 대해서 말씀드리겠습니다.
저는 외부링크를 새창으로 띄우는 것이 사실 공급자적 입장에서 사이트를 빠져나가지 못하게하는 기능으로 느껴지고, 이를 상당히 불편하게 생각합니다. 조금만 서핑을 해도 브라우져에 탭이 수십개가 떠있거든요.
저는 사이트를 좀 이곳 저곳 타고 다니면서 보고 싶은 사이트들을 Shift + 클릭으로 새탭으로 남기고 또 돌아다니고 각 탭별로 비교하면서 보다보니 탭을 굉장히 많이 열어놓는 편인데요. 외부링크를 열때마다 탭을 열었다, 닫았다, 다시 원페이지의 탭을 찾고 하는것이 훨씬더 불편하다고 생각을 합니다. 백스페이스 한번이면 충분한데 말이죠.
모바일에서는 더 합니다. 새창이 한번뜨면 다시 열린페이지 목록으로가서 원 페이지를 찾아야합니다. 중간에 페이지를 여럿 띄웠다면 또 원 페이지를 위아래로 찾아야 합니다. 현재는 좌에서 우로 스와이프 한번이면 다시 돌아올 수 있습니다.


위는 지극히 제 취향을 설명드렸습니다.
문제는 취향이 아닌 취향을 선택할 여지를 줄 수 있는지 없는지 라고 봅니다.
현재 상태에서는 새창을 띄울지 말지를 사용자가 스스로 선택할 수 있지만, 새창을 강제할 경우 이는 사용자 선택은 무시 됩니다.

대부분 User Interface를 구성할 때 제 1원칙으로 놓는 것이 'Place Users in Control'  입니다.
즉 사용자가 직접 선택할 수 있게 두는것입니다. 사용자의 선택을 강제할 수록 좋은 UI 가 아니라는 얘기겠죠.

- [The Golden Rules of User Interface Design](http://theomandel.com/wp-content/uploads/2012/07/Mandel-GoldenRules.pdf)
- [Top 10 Mistakes in Web Design](http://www.nngroup.com/articles/top-10-mistakes-web-design/)

그리고 문론 그의 대한 반론도 있고 그 주장도 분명 타당합니다.

- [Why External Links Should Open in New Tabs](http://uxmovement.com/navigation/why-external-links-should-open-in-new-tabs/)

위 링크에 내용과 댓글을 보시면 이 단순한 문제가 얼마나 첨예한지 아실수 있습니다. 재밌습니다.

결국 우선 제가 선택한 방식은 강제 보단 '사용자 선택'을 '선택' 했습니다. 
물론 앞서 말씀드렸듯이 제 취향이 전혀 반영되지 않았다고 말씀드리진 않겠습니다.
하지만 우리는 개발자이고 개발자를 위한 사이트 이기 때문에, 관성에 의한 편안함은 경계해야된다고 생각합니다.

**Comment by 1angerhans** [comment]
그리고 참고로 구글은 .com 은 현재창에서 뜨고, .co.kr 은 새창으로 뜹니다.
예전에는 .co.kr 에서는 '새창으로 띄우기' 링크를 제공했었는데, 근래에 새창으로 완전히 변경되었습니다.
페이스북은 무한스크롤 페이지 특성상 되돌아왔을때 상태 유지가 힘들다는 단점이 있어서, 새창으로밖에 안될껍니다.
그래서 페북은 내부 링크도 대부분의 컨텐츠를 팝업으로 처리해놨죠.

**Comment by ssoju** [comment]
말씀듣고 보니 강제시키는건 문제가 있는듯 하네요..^^
유저가 현재 기능에 익숙해지면 스스로 원하는대로 띄워서 보리라 생각되어지구요.^^

**Comment by yjc0703** [comment]
[새창으로 띄우기] 버튼도 자동으로 생성해주면 어떨까요?
작업양이 많을까요?

**Comment by 1angerhans** [comment]
@yjc0703 자동링크에 대해서는 새창 기능을 넣는것은 크게 어렵지 않습니다. 해당 기능에 대해서는 한번 검토해 보겠습니다.

**Comment by javajjang** [comment]
@1angerhans 개인적인 생각입니다만 대부분의 사이트들은 컨텐츠 중심이지만 오키와 같은 개발자 커뮤니티에 걸린 링크들은 해당 내용을 뒷받침하거나 참조할만한 링크가 아닐까 합니다.
(사실 몇년만에 들어오는거라 최근엔 잘 모르겠습니다 ^^;)
암튼 그래서 링크는 참조로 봐야하고 본문은 계속 읽어 내려가야 하는 상황이 아닐까 합니다 ^^

이건 맞다 틀리다의 문제는 아닌것같구요 말씀하신 "하지만 우리는 개발자이고 개발자를 위한 사이트 이기 때문에, 관성에 의한 편안함은 경계해야된다고 생각합니다." 공감합니다

암튼 지금은 다른 사이트들에서도 마찬가지지만 Ctrl도 익숙해져서 괜찮습니다 ㅎㅎ

**Comment by 1angerhans** [comment]
@javajjang 의견 감사합니다. 그럼 혹시 지금의 불편함이 @yjc0703 님께서 제시하신 방식으로 기능을 제공할 경우 불편함이 많이 줄어들까요? 
사실 wiki 같은 서비스에서 비슷한 기능을 제공하는데 효용성이 있는지는 조금 의문이라서요.

**Comment by javajjang** [comment]
@1angerhans 굳이 그렇게까지 할 필요가 있을까요?? 그건 이미 Ctrl로 충분하다고 생각합니다 ^^;

**Comment by yjc0703** [comment]
저도 okky 사용 중 무의식적으로 ctrl 없이 링크를 클릭한 후 창을 닫아버리는 일이 종종 있답니다 ㅠㅠ
웹표준 가이드에서도 링크는 해당 창에서 오픈되도록 유도하고 있기는 하지만 모두가 좋아하는 방식은 아니라고 생각합니다. 그래서 이런 이슈도 나오게 되었겠지요? 아마 말씀은 안하셔도 불편하다고 느끼는 분들이 계실거라 생각합니다.

현재 에디터에서 url 을 붙여넣으면 자동으로 링크를 생성해주는 구조이기 때문에 새창열기용 링크를 하나 더 만드는데 큰 어려움이 없을것으로 생각되어 제안드려봤습니다. 또 구글에서 지원하던 방식이기도 하구요.

사실은 아무렇게나 방치되어 있던 왼손을 키보드로 옮기기 귀찮아서랍니다 ^^;;

**Comment by 1angerhans** [comment]
@yjc0703 I agreed. 우선 자동링크에 대해서 끝에 새창아이콘 넣는것으로 하겠습니다.
