### ISSUE TITLE
mac safari에서 화면 깨짐 현상

### ISSUE THREAD

**Issue by dotkebi** [okjsp/okky#71]
![2015-04-09 9 17 51](https://cloud.githubusercontent.com/assets/8197507/7058273/31ac30d8-de9a-11e4-8d23-251c71bb6533.png)

사파리 화면 폭을 좁힌 상태에서 좌우 스크롤을 하면 위와 같이
본문 영역이 좌측 메뉴 영역을 침범합니다.

크롬에서도 동일하네요.

**Comment by 1angerhans** [comment]
z-index 문젠거 같은데... 저도 맥에 사파리인데 저는 해당 상태가 재현이 안되는군요. 이상하네요.

**Comment by neoburi** [comment]
가로 크기 줄인 후에컨텐츠가 좌측 메뉴바에 숨겨지도록 스크롤 하고 링크에 마우스 오버하면 그런 현상이 나타납니다.

**Comment by 1angerhans** [comment]
감사합니다. 오늘 저녁에 수정된 부분 반영하도록 하겠습니다.
