### ISSUE TITLE
405 error

### ISSUE THREAD

**Issue by egg-cat** [okjsp/okky#74]
접근경로 
비로그인 - 스크랩 - 로그인유도 - 페이스북로그인 - 해당결과 도출.

**Comment by egg-cat** [comment]
현재 -페이스북 로그인 실패- This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

일반방식(아이디 로그인) 시도 시 - 인증되지 않은 계정입니다. 이메일 인증을 완료해 주시기 바랍니다.- 라고 뜨며 로그인 실패처리.
+ 추가 재인증메일 발송 프로세스가 필요할거같기도해요.

**Comment by kwamuki** [comment]
@egg-cat 페이스북 APP 설정 문제였습니다. 수정 되었습니다.

**Comment by 1angerhans** [comment]
term url을 안넣어서 개발 모드로 강제변경 되었네요. 수정되었습니다.
그리고 추가 재인증메일은 '계정 찾기' 를 통해서 가능합니다.

페북 로그인에 대해서 확인 후 정상작동하면 #75 이슈 close 해주세요.
