### ISSUE TITLE
작성자 클릭 user/info들어가서 활동점수 클릭하면 HTTP404에러

### ISSUE THREAD

**Issue by kwamuki** [okjsp/okky#82]
http://okky.kr/article/281332
---
작성자 클릭 user/info들어가서 활동점수 클릭하면
HTTP404에러 뜨는데, user/info/index.gsp" not found 뜨는 거 보니  index.jsp를 gsp로 오타나셨나봐요.

**Comment by yjc0703** [comment]
링크의 href="" 를 브라우저마다 처리하는 방식이 달라서 그렇습니다.
오류는 IE에서 발생되고 있으며 링크를 빼거나 hash 를 넣어주면 해결될 것으로 보입니다.
