### ISSUE TITLE
댓글 수정 시 버그

### ISSUE THREAD

**Issue by ProTech87** [okjsp/okky#83]
웹 브라우저는 IE 11입니다.
댓글 작성 후 바로 수정하려 할 때 이전에 등록되어 있던 글이 채워집니다.

예를 들어보겠습니다.
123을 등록한 후 수정해서 12345로 수정합니다.
그 후 다시 수정을 하려고 하면 123이 채워져 있습니다.

**Comment by yjc0703** [comment]
테스트를 진행해 보았습니다. 확인을 부탁드립니다.

크롬
1. 게시글 작성 > 게시글 수정 클릭 > 수정완료 후 보기 > 게시글 수정 클릭 > 수정된 데이터 노출
2. 게시글 작성 > 게시글 수정 클릭 > 수정완료 후 보기 > 뒤로가기 > 수정된 데이터 노출

IE
3. 게시글 작성 > 게시글 수정 클릭 > 수정완료 후 보기 > 게시글 수정 클릭 > 수정된 데이터 노출
4. 게시글 작성 > 게시글 수정 클릭 > 수정완료 후 보기 > 뒤로가기 > 수정 전 데이터 노출

답변을 부탁드립니다.
3. 의 경우에도 본문에 작성해주신 오류가 나타나는지요?
4, 의 경우도 수정이 필요한 것인지요?

감사합니다.
