### ISSUE TITLE
개발환경 문서화

### ISSUE THREAD

**Issue by herblover** [okjsp/okky#9]
처음 Project를 Fork 한 이후부터, 개발 시작할 수 있는 수준 까지 따라갈 수 있는 문서화가 필요합니다.

* GVM 을 사용할지 여부 (만약에 사용한다면 설치법 포함)
* IDE등과 연동할지 여부 (만약에 연동한다면, .gitignore 에 있는 내용에 대한 설명도 포함)
* MariaDB 등에 대한 Boostrapping

등에 대한 내용이 README.md 쪽에 문서화 되는 쪽이 참여를 늘릴 수 있는 방법으로 보입니다.

**Comment by kwamuki** [comment]
@herblover 네, 준비하겠습니다. ^^
혹시 참고할 만한 좋은 레퍼런스 있으면 알려주시면 많은 도움이 되겠습니다.

**Comment by herblover** [comment]
@kwamuki 사실 처음 Clone 한 후에 코딩에 들어가는 시간 까지가 프로젝트 접근성에 꽤 영향을 준다고 생각해서요. ^^;
https://github.com/google/iosched/blob/master/doc/BUILDING.md
이런형태의 단순한 Build Instruction 정도면 충분할 것으로 보입니다~

**Comment by kwamuki** [comment]
@herblover 네, 감사합니다. :smile:

**Comment by 1angerhans** [comment]
우선 프로젝트를 돌려볼 수 있는 수준의 간단한 정보 부터 시작하여 소스를 받으신 분들의 피드백을 받으면서 계속 추가하는 방식으로 작업하려고 합니다.
다행히도 옆에 마루타가 되어주실만한 분이....쿨럭...

**Comment by herblover** [comment]
넵~ OS X 쪽이나, GVM 쪽 관련해서는 제가 일부 도울수도 있을것 같습니다~ 문서 올려 주시면 저도 일부 작업해서 Pull Request 보낼께요~

**Comment by sbroh** [comment]
너무 고마와..  ㅠㅜ
2015. 2. 10. 오후 5:45에 "Kenny Kang" <notifications@github.com>님이 작성:

**Comment by kenu** [comment]
http://okky.kr/article/272699
Windows 7용 소스 실행 환경입니다. 
2번째는 소스 개발 환경 준비해서 올리겠습니다.

**Comment by kwamuki** [comment]
@kenu 정말 감사합니다. :smile:
