### ISSUE TITLE
회원가입 인증 메일 문제

### ISSUE THREAD

**Issue by ragrasia** [okjsp/okky#98]
okky에 가입을 하고 싶어서 구글로 소셜 로그인 한뒤 회원가입을 했습니다.

소셜 로그인(구글)을 사용했기 때문에 저 스스로 입력 문제는 아니라고 생각해서 이리 올려 봅니다.
![default](https://cloud.githubusercontent.com/assets/1639095/13042587/b033cde8-d404-11e5-9581-fc77e403581e.JPG)

다시 인증 메일을 받을 수단도 없어서 이도 저도 못하는 데 이런 경우에 대한 대처가 있었으면 좋겠습니다.

또한 페이스북으로 로그인 버튼을 클릭 하니 회원가입시 작성했던 닉네임으로 로그인이 됩니다.
![default](https://cloud.githubusercontent.com/assets/1639095/13042672/5efd27ca-d405-11e5-8794-199efddfc9e8.JPG)

제가 무언가 잘 못 알고 있는 건지 혼란이 오는 부분입니다.

**Comment by 1angerhans** [comment]
구글 로그인으로 가입할 경우는 메일인증을 하지 않는데, 어떤 경우인지 확인 할 필요가 있을 것 같습니다.
혹시 btjung@okky.kr 로 닉네임 알려주실 수 있으신가요?
